### ISSUE TITLE
pip install cntext报错了

### ISSUE THREAD

**Issue by kanbang** [hiDaDeng/cntext#3]
非常棒的项目！执行install的时候提示依赖冲突 
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\zhai\AppData\Local\Temp\tmpxcpx8xec'
       cwd: C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027
  Complete output (45 lines):
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 319, in <module>
      setup_package()
    File "setup.py", line 315, in setup_package
      setup(**metadata)
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "setup.py", line 201, in configuration
      config.add_subpackage("sklearn")
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 982, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 924, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn\setup.py", line 85, in configuration
      cythonize_extensions(top_path, config)
    File "C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027\sklearn\_build_utils\__init__.py", line 47, in cythonize_extensions
      basic_check_build()
    File "C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027\sklearn\_build_utils\pre_build_helpers.py", line 113, in basic_check_build
      compile_test_program(code)
    File "C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027\sklearn\_build_utils\pre_build_helpers.py", line 70, in compile_test_program
      ccompiler.compile(
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e1/4d/15c3542a17eebf61e48bd71dc55b5f3b5031f1cd0dc4aad1ff9ac9651e49/scikit-learn-1.0.tar.gz#sha256=776800194e757cd212b47cd05907e0eb67a554ad333fe76776060dbb729e3427 (from https://pypi.org/simple/scikit-learn/) (requires-python:>=3.7). Command errored out with exit status 1: 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\zhai\AppData\Local\Temp\tmpxcpx8xec' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement scikit-learn==1.0 (from cntext) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2)
ERROR: No matching distribution found for scikit-learn==1.0

**Comment by hiDaDeng** [comment]
错误提示电脑缺Microsoft Visual C++ 14.0，

Get it with "Microsoft C++ Build Tools":&nbsp;https://visualstudio.microsoft.com/visual-cpp-build-tools/
配置好Microsoft Visual C++ 14.0之后再安装cntext应该就没问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiDaDeng/cntext"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午4:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hiDaDeng/cntext] pip install cntext报错了 (Issue #3)





 
非常棒的项目！执行install的时候提示依赖冲突
 ERROR: Command errored out with exit status 1:
 command: 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pep517\in_process_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\zhai\AppData\Local\Temp\tmpxcpx8xec'
 cwd: C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027
 Complete output (45 lines):
 Partial import of sklearn during the build process.
 Traceback (most recent call last):
 File "C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pep517\in_process_in_process.py", line 363, in 
 main()
 File "C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pep517\in_process_in_process.py", line 345, in main
 json_out['return_val'] = hook(**hook_input['kwargs'])
 File "C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pep517\in_process_in_process.py", line 164, in prepare_metadata_for_build_wheel
 return hook(metadata_directory, config_settings)
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in prepare_metadata_for_build_wheel
 self.run_setup()
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
 super(_BuildMetaLegacyBackend,
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
 exec(compile(code, file, 'exec'), locals())
 File "setup.py", line 319, in 
 setup_package()
 File "setup.py", line 315, in setup_package
 setup(**metadata)
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
 config = configuration()
 File "setup.py", line 201, in configuration
 config.add_subpackage("sklearn")
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in add_subpackage
 config_list = self.get_subpackage(subpackage_name, subpackage_path,
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 982, in get_subpackage
 config = self._get_configuration_from_setup_py(
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 924, in get_configuration_from_setup_py
 config = setup_module.configuration(*args)
 File "sklearn\setup.py", line 85, in configuration
 cythonize_extensions(top_path, config)
 File "C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027\sklearn_build_utils_init.py", line 47, in cythonize_extensions
 basic_check_build()
 File "C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027\sklearn_build_utils\pre_build_helpers.py", line 113, in basic_check_build
 compile_test_program(code)
 File "C:\Users\zhai\AppData\Local\Temp\pip-install-7fm07fnp\scikit-learn_18bc65c4a6ae4a82a5262495d22e2027\sklearn_build_utils\pre_build_helpers.py", line 70, in compile_test_program
 ccompiler.compile(
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools_distutils_msvccompiler.py", line 327, in compile
 self.initialize()
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools_distutils_msvccompiler.py", line 224, in initialize
 vc_env = _get_vc_env(plat_spec)
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
 return _msvc14_get_vc_env(plat_spec)
 File "C:\Users\zhai\AppData\Local\Temp\pip-build-env-i50shpmd\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
 raise distutils.errors.DistutilsPlatformError(
 distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
 
WARNING: Discarding https://files.pythonhosted.org/packages/e1/4d/15c3542a17eebf61e48bd71dc55b5f3b5031f1cd0dc4aad1ff9ac9651e49/scikit-learn-1.0.tar.gz#sha256=776800194e757cd212b47cd05907e0eb67a554ad333fe76776060dbb729e3427 (from https://pypi.org/simple/scikit-learn/) (requires-python:&gt;=3.7). Command errored out with exit status 1: 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\zhai\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pep517\in_process_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\zhai\AppData\Local\Temp\tmpxcpx8xec' Check the logs for full command output.
 ERROR: Could not find a version that satisfies the requirement scikit-learn==1.0 (from cntext) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2)
 ERROR: No matching distribution found for scikit-learn==1.0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kanbang** [comment]
可以了，谢谢
